baseURL = 'http://herwhiskers.github.io/'
languageCode = 'zh-cn'
title = 'A Purrception'
theme = 'stack'
[menu]
         [[menu.main]]
            identifier = "rss"
            name = "RSS"
            url = "/index.xml"
            weight = 5
